from __future__ import annotations

from typing import Dict

from ..fund_os.mandates import FundMandate


def default_family_mandates() -> Dict[str, FundMandate]:
    return {
        "flash_arb": FundMandate(
            "flash_arb",
            ["dex", "private_relay"],
            0.32,
            "very_high",
            4.0,
            ["PRIVATE", "PROTECTED"],
            1.0,
            "deep",
            "atomic_exit",
            "production",
            ["flashloan", "internal_prime"],
            ["internal_capital", "pilot_capital", "private_fund", "institutional_scale"],
        ),
        "funding_arb": FundMandate(
            "funding_arb",
            ["cex", "perp"],
            0.22,
            "medium",
            6.0,
            ["PROTECTED", "PUBLIC"],
            2.0,
            "medium",
            "hedged",
            "production",
            ["treasury", "internal_prime"],
            ["pilot_capital", "friends_family", "private_fund", "institutional_scale"],
        ),
        "cex_dex_arb": FundMandate(
            "cex_dex_arb",
            ["cex", "dex"],
            0.18,
            "high",
            5.0,
            ["PROTECTED", "PRIVATE"],
            1.2,
            "medium",
            "cross_venue_hedge",
            "capped_live",
            ["treasury", "internal_prime"],
            ["internal_capital", "pilot_capital", "private_fund"],
        ),
        "cex_cex_arb": FundMandate(
            "cex_cex_arb",
            ["cex"],
            0.18,
            "high",
            5.0,
            ["PUBLIC", "PROTECTED"],
            1.5,
            "medium",
            "cross_exchange_net",
            "capped_live",
            ["treasury", "internal_prime"],
            ["pilot_capital", "friends_family", "private_fund"],
        ),
        "liquidation_capture": FundMandate(
            "liquidation_capture",
            ["onchain", "private_relay"],
            0.16,
            "burst",
            5.0,
            ["PRIVATE", "PROTECTED"],
            1.0,
            "deep",
            "immediate_exit",
            "shadow_live",
            ["flashloan", "treasury"],
            ["internal_capital", "pilot_capital"],
        ),
        "mev_search": FundMandate(
            "mev_search",
            ["private_relay", "builder"],
            0.12,
            "burst",
            3.0,
            ["PRIVATE"],
            1.0,
            "deep",
            "protected_only",
            "shadow_live",
            ["flashloan", "internal_prime"],
            ["internal_capital", "pilot_capital"],
        ),
        "volatility_market_making": FundMandate(
            "volatility_market_making",
            ["cex", "amm"],
            0.14,
            "continuous",
            4.0,
            ["PUBLIC", "PROTECTED"],
            1.5,
            "medium",
            "inventory_rebalance",
            "paper",
            ["treasury", "internal_prime"],
            ["pilot_capital", "friends_family"],
        ),
        "stat_arb": FundMandate(
            "stat_arb",
            ["cex", "dex"],
            0.14,
            "medium",
            5.0,
            ["PUBLIC", "PROTECTED"],
            1.5,
            "medium",
            "pair_hedge",
            "paper",
            ["treasury", "internal_prime"],
            ["pilot_capital", "friends_family", "private_fund"],
        ),
        "treasury_yield": FundMandate(
            "treasury_yield",
            ["treasury"],
            0.25,
            "low",
            2.0,
            ["PUBLIC"],
            1.0,
            "shallow",
            "duration_limit",
            "production",
            ["treasury"],
            [
                "internal_capital",
                "pilot_capital",
                "friends_family",
                "private_fund",
                "institutional_scale",
            ],
        ),
    }
