import type { CommandCenterSnapshot } from "./types";

function demoNowMs(): number {
  // Fixed timestamp for deterministic offline demo rendering.
  return 1_725_000_000_000;
}

export const DEMO_SNAPSHOT: CommandCenterSnapshot = {
  ok: true,
  portfolio: {
    navUsd: 13982.12,
    pct24h: 0.62,
    pct7d: 3.18,
    drawdownPct: 1.2,
    state: "active",
    updatedAtMs: demoNowMs(),
  },
  controlMode: "assist",
  pausedReason: "Assist mode keeps live scanning on while autonomous execution stays off.",
  rpcDegraded: false,
  dataSource: "mock",
  liveMode: "demo",
  sourceLabel: "Deterministic demo seed",
  engines: [
    { engineId: "cross_cex_dex", title: "Cross CEX + DEX", mode: "observe_only", lifecycle: "sandbox", opportunities: 3, admitted: 1, blocked: 2, capitalCapPct: 8, confidenceFloor: 0.62, reason: "Demo engine summary" },
    { engineId: "funding_arb", title: "Funding Carry", mode: "observe_only", lifecycle: "paper", opportunities: 2, admitted: 1, blocked: 1, capitalCapPct: 10, confidenceFloor: 0.58 },
    { engineId: "cross_chain_arb", title: "Cross Chain", mode: "capped_live", lifecycle: "observe_only", opportunities: 1, admitted: 0, blocked: 1, capitalCapPct: 4, confidenceFloor: 0.75, reason: "Inventory not prepositioned" },
    { engineId: "mev_search", title: "MEV Search", mode: "private_only", lifecycle: "capped_live", opportunities: 4, admitted: 2, blocked: 2, capitalCapPct: 6, confidenceFloor: 0.7 },
  ],
  wealthGoal: {
    targetReturnPct: 8,
    timeframeDays: 14,
    riskTolerance: "moderate",
    currentReturnPct: 3.18,
    progressPct: 39.75,
    goalAchieved: false,
    suggestedNextTargetPct: 9.2,
    maxDrawdownPct: 10,
    capitalCommitmentPct: 25,
  },
  aiIntent: {
    intent: "Harvest short-lived atomic edges; compound winnings into base borrow with capped risk.",
    confidence: 0.78,
    strategies: ["flashloan_atomic/v3_tri", "flashloan_atomic/v2_v3_bridge"],
  },
  exposure: { activePct: 62, sandboxPct: 12, idlePct: 21, atRiskPct: 5 },
  alerts: [
    {
      id: "al_regime",
      tsMs: demoNowMs() - 12 * 60_000,
      severity: "warn",
      title: "Regime shift: volatility rising",
      detail: "Confidence 0.74 → defensive clamps ready if drawdown velocity increases.",
    },
    {
      id: "al_drift",
      tsMs: demoNowMs() - 37 * 60_000,
      severity: "info",
      title: "Model drift watch",
      detail: "Confidence vs reality gap stable; no rollback required.",
    },
  ],
  allocations: [
    { id: "s1", name: "Atomic V3 Tri", capitalUsd: 7020, roiPct: 11.8, volPct: 4.2, riskScore: 34, status: "active" },
    { id: "s2", name: "Atomic V2↔V3 Bridge", capitalUsd: 3650, roiPct: 8.2, volPct: 5.5, riskScore: 41, status: "active" },
    { id: "s3", name: "Sandbox Mutations", capitalUsd: 1650, roiPct: 0.9, volPct: 9.3, riskScore: 62, status: "sandbox" },
    { id: "s4", name: "Probation Variant", capitalUsd: 980, roiPct: 2.1, volPct: 6.7, riskScore: 55, status: "probation" },
  ],
  capitalFlows: [
    {
      id: "cf1",
      tsMs: demoNowMs() - 2 * 3600_000,
      from: "Idle",
      to: "Atomic V3 Tri",
      amountUsd: 400,
      triggeredBy: "ai",
      why: "Edge density above threshold; gas normalized PnL positive.",
      riskResult: "approved",
      execSummary: "32 trades, 93% success, avg slip 0.06%.",
    },
    {
      id: "cf2",
      tsMs: demoNowMs() - 4 * 3600_000,
      from: "Sandbox",
      to: "Probation Variant",
      amountUsd: 250,
      triggeredBy: "operator",
      why: "Approved proposal #M-17 with 25-trade probation cap.",
      riskResult: "clamped",
      execSummary: "Probation cap 2.5% NAV; defensive clamps enabled.",
    },
  ],
  decisions: [
    {
      id: "d1",
      tsMs: demoNowMs() - 6 * 60_000,
      intent: "Execute atomic v3 triangle WETH→USDC→WBTC→WETH",
      confidence: 0.81,
      strategies: ["flashloan_atomic/v3_tri"],
      outcome: "success",
      reward: 0.74,
      notes: "MEV guard: protected send, tight deadline.",
    },
    {
      id: "d2",
      tsMs: demoNowMs() - 12 * 60_000,
      intent: "Skip: gas anomaly would erase edge",
      confidence: 0.92,
      strategies: ["flashloan_atomic/v3_tri"],
      outcome: "skipped",
      reward: 0.18,
      notes: "Risk engine vetoed. Capital preserved.",
    },
  ],
  regime: {
    current: "choppy-high-gas",
    confidence: 0.74,
    history: [
      { tsMs: demoNowMs() - 24 * 3600_000, regime: "calm-low-gas" },
      { tsMs: demoNowMs() - 12 * 3600_000, regime: "choppy" },
      { tsMs: demoNowMs() - 2 * 3600_000, regime: "choppy-high-gas" },
    ],
  },
  risk: {
    composite: 37,
    caps: { maxDailyLossPct: 3, maxExposurePct: 80, sandboxCapPct: 10, probationCapPct: 2.5 },
    breakers: { drawdownBreaker: false, gasAnomalyBreaker: true, driftBreaker: false },
  },
  governance: {
    v1Focus: "flashloan_atomic",
    aiAuthority: "bounded",
    controlMode: "assist",
    governanceEnabled: true,
    mutationEnabled: false,
    evolutionFrozen: true,
    allocationsFrozen: false,
    sandboxOnly: false,
    paused: false,
  },
  governanceHistory: [
    {
      id: "g1",
      tsMs: demoNowMs() - 6 * 3600_000,
      actor: "operator",
      action: "Freeze evolution",
      reason: "Stabilize v1 flashloan atomic baseline.",
      before: { evolutionFrozen: false },
      after: { evolutionFrozen: true },
      hash: "demo_hash_2",
      prevHash: "demo_hash_1",
    },
  ],
  sandbox: {
    sandboxNavUsd: 1650,
    probationTradesLeft: 17,
    proposals: [
      {
        id: "m17",
        tsMs: demoNowMs() - 9 * 3600_000,
        title: "Tighten min_p_success 0.70 → 0.75",
        summary: "Reduces false positives under choppy gas; may reduce volume.",
        expectedDeltaPct: 1.4,
        riskDelta: -6,
        probationCapPct: 2.5,
        status: "queued",
      },
    ],
  },
  analytics: {
    equity: Array.from({ length: 40 }).map((_, i) => ({
      tsMs: demoNowMs() - (40 - i) * 3600_000,
      navUsd: 12000 + i * 45 + (i % 5 === 0 ? -35 : 0),
      regime: i < 18 ? "calm" : i < 30 ? "choppy" : "choppy-high-gas",
    })),
    utilizationPct: 62,
    returnPerRisk: 0.42,
    execSuccessPct: 91,
    slippagePct: 0.08,
    complexityCost: 0.21,
  },
  observability: {
    loopMsP50: 420,
    loopMsP90: 960,
    loopMsP99: 1400,
    rpcErrRate: 0.03,
    oppsSeen: 184,
    oppsExecutable: 21,
    execLatencyMsP50: 1200,
    execLatencyMsP90: 1850,
    execLatencyMsP99: 2600,
    submitToReceiptMsP50: 1600,
    submitToReceiptMsP90: 4200,
    submitToReceiptMsP99: 8000,
  },
};
